<template>
  <div>
    <b-button @click="modal = true" class="is-success">{{ text }}</b-button>
    <b-modal v-model="modal" trap-focus has-modal-card>
      <div class="modal-card" style="width: auto">
        <header class="modal-card-head">
          <p class="modal-card-title">Create New Manufacturer</p>
        </header>
        <section class="modal-card-body">
          <b-field
            label="Name"
            :type="{ 'is-danger': errors.name }"
            :message="errors.name"
          >
            <b-input v-model="manufacturer.name" />
          </b-field>
          <b-field
            label="Slug"
            message="This is optional, and will be autogenerated if left blank."
          >
            <b-input v-model="manufacturer.slug" />
          </b-field>
        </section>
        <footer class="modal-card-foot">
          <b-button label="Close" @click="modal = false" />
          <b-button label="Create" type="is-primary" @click="submit" />
        </footer>
      </div>
    </b-modal>
  </div>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      default: 'Create Manufacturer',
    },
  },
  data() {
    return {
      errors: {},
      manufacturer: {
        name: '',
        slug: null,
      },
      modal: false,
    }
  },
  methods: {
    async submit() {
      try {
        let resp = await this.$axios.post(`/manufacturers/`, this.manufacturer)
        this.$buefy.toast.open({
          message: 'Created new Manufacturer.',
          type: 'is-success',
        })
        this.$emit('manufacturerCreated', resp.data.slug)
        this.errors = {}
        this.manufacturer = {
          name: '',
          slug: null,
        }
        this.modal = false
      } catch (error) {
        if (error.response) {
          this.handleError(error)
        } else {
          this.$buefy.toast.open({
            message: error.message,
            type: 'is-danger',
          })
        }
      }
    },
    handleError(error) {
      if (error.response.status == 400) {
        this.$buefy.toast.open({
          message:
            'Unable to create Manufacturer. Please check the form for errors.',
          type: 'is-danger',
        })
        this.errors = error.response.data
      } else {
        this.$buefy.toast.open({
          message: error.response.data.detail,
          type: 'is-danger',
        })
      }
    },
  },
}
</script>
