<template>
  <section>
    <b-field
      label="Name"
      :type="{ 'is-danger': errors.name }"
      :message="errors.name"
    >
      <b-input v-model="manufacturer.name" />
    </b-field>
    <b-field
      label="Slug"
      message="This is optional, and will be autogenerated if left blank."
    >
      <b-input v-model="manufacturer.slug" />
    </b-field>
    <b-button @click="submit">Create</b-button>
  </section>
</template>

<script>
export default {
  data() {
    return {
      errors: {},
      manufacturer: {
        name: '',
        slug: null,
      },
    }
  },
  methods: {
    async submit() {
      try {
        let resp = await this.$axios.post(`/manufacturers/`, this.manufacturer)
        this.$buefy.toast.open({
          message: 'Created new Manufacturer.',
          type: 'is-success',
        })
        this.$emit('success', resp.data.slug)
      } catch (error) {
        if (error.response) {
          this.handleError(error)
        } else {
          this.$buefy.toast.open({
            message: error.message,
            type: 'is-danger',
          })
        }
      }
    },
    handleError(error) {
      if (error.response.status == 400) {
        this.$buefy.toast.open({
          message:
            'Unable to create Manufacturer. Please check the form for errors.',
          type: 'is-danger',
        })
        this.errors = error.response.data
      } else {
        this.$buefy.toast.open({
          message: error.response.data.detail,
          type: 'is-danger',
        })
      }
    },
  },
}
</script>
