<template>
  <div>
    <b-button @click="modal = true" class="is-success">{{ text }}</b-button>
    <b-modal v-model="modal" trap-focus has-modal-card>
      <div class="modal-card" style="width: auto">
        <header class="modal-card-head">
          <p class="modal-card-title">Create New Asset Model</p>
        </header>
        <section class="modal-card-body">
          <b-field label="Name">
            <b-input v-model="model.name"></b-input>
          </b-field>
          <b-field
            label="Slug"
            message="This is optional, and will be autogenerated if left blank."
          >
            <b-input v-model="model.slug"></b-input>
          </b-field>

          <b-field label="Manufacturer">
            <b-select
              placeholder="Select a manufacturer"
              v-model="model.manufacturer_slug"
              :loading="manufacturers == null"
            >
              <option
                v-for="manufacturer in manufacturers"
                :value="manufacturer.slug"
                :key="manufacturer.slug"
              >
                {{ manufacturer.name }}
              </option>
            </b-select>
            <manufacturer-create-modal text="+" />
          </b-field>
          <b-field label="Can Contain Assets">
            <b-switch v-model="model.is_container"></b-switch>
          </b-field>
        </section>
        <footer class="modal-card-foot">
          <b-button label="Close" @click="modal = false" />
          <b-button label="Create" type="is-primary" @click="submit" />
        </footer>
      </div>
    </b-modal>
  </div>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      default: 'Create Asset Model',
    },
  },
  data() {
    return {
      errors: {},
      model: {
        name: '',
        slug: null,
        manufacturer_slug: null,
        is_container: null,
      },
      modal: false,
      manufacturers: null,
    }
  },
  methods: {
    async fetch() {
      try {
        let resp = await this.$axios.get('/manufacturers/?ordering=name')
        this.manufacturers = resp.data.results // TODO: Handle pagination correctly!
      } catch (error) {
        this.$buefy.toast.open({
          message: error.message,
          type: 'is-danger',
        })
      }
    },
    async submit() {
      try {
        let resp = await this.$axios.post(`/manufacturers/`, this.manufacturer)
        this.$buefy.toast.open({
          message: 'Created new Manufacturer.',
          type: 'is-success',
        })
        this.$emit('manufacturerCreated', resp.data.slug)
        this.modal = false
      } catch (error) {
        if (error.response) {
          this.handleError(error)
        } else {
          this.$buefy.toast.open({
            message: error.message,
            type: 'is-danger',
          })
        }
      }
    },
    handleError(error) {
      if (error.response.status == 400) {
        this.$buefy.toast.open({
          message:
            'Unable to create Manufacturer. Please check the form for errors.',
          type: 'is-danger',
        })
        this.errors = error.response.data
      } else {
        this.$buefy.toast.open({
          message: error.response.data.detail,
          type: 'is-danger',
        })
      }
    },
  },
}
</script>
