<template>
  <div>
    <b-button
      @click="modal = true"
      :disabled="$auth.loggedIn == false"
      class="is-success"
      >{{ text }}</b-button
    >
    <b-modal v-model="modal" trap-focus has-modal-card>
      <div class="modal-card" style="width: auto">
        <header class="modal-card-head">
          <p class="modal-card-title">Create New Asset Model</p>
        </header>
        <section class="modal-card-body">
          <b-field
            label="Name"
            :type="{ 'is-danger': errors.name }"
            :message="errors.name"
          >
            <b-input v-model="model.name"></b-input>
          </b-field>
          <b-field
            label="Slug"
            message="This is optional, and will be autogenerated if left blank."
          >
            <b-input v-model="model.slug"></b-input>
          </b-field>
          <manufacturer-input
            v-model="model.manufacturer_slug"
            :type="{ 'is-danger': errors.name }"
            :message="errors.name"
          />
          <b-field label="Can Contain Assets">
            <b-switch v-model="model.is_container"></b-switch>
          </b-field>
        </section>
        <footer class="modal-card-foot">
          <b-button label="Close" @click="modal = false" />
          <b-button label="Create" type="is-primary" @click="submit" />
        </footer>
      </div>
    </b-modal>
  </div>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      default: 'Create',
    },
  },
  data() {
    return {
      errors: {},
      model: {
        name: '',
        slug: null,
        manufacturer_slug: null,
        is_container: false,
      },
      modal: false,
    }
  },
  methods: {
    async submit() {
      try {
        let resp = await this.$axios.post(`/asset-models/`, this.model)
        this.$buefy.toast.open({
          message: 'Created new Asset Model.',
          type: 'is-success',
        })
        this.$emit('modelCreated', resp.data.slug)
        this.modal = false
      } catch (error) {
        if (error.response) {
          this.handleError(error)
        } else {
          this.$buefy.toast.open({
            message: error.message,
            type: 'is-danger',
          })
        }
      }
    },
    handleError(error) {
      if (error.response.status == 400) {
        this.$buefy.toast.open({
          message:
            'Unable to create Asset Model. Please check the form for errors.',
          type: 'is-danger',
        })
        this.errors = error.response.data
      } else {
        this.$buefy.toast.open({
          message: error.response.data.detail,
          type: 'is-danger',
        })
      }
    },
  },
}
</script>
